# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"\x90\x01\n\x08\x44ocument\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x02 \x01(\t\x12\x30\n\x08metadata\x18\x03 \x03(\x0b\x32\x1e.search.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x92\x01\n\x0cQueryRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x32\n\x07\x66ilters\x18\x03 \x03(\x0b\x32!.search.QueryRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xe0\x01\n\rQueryResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.search.StatusCode\x12M\n\x16\x66ile_name_to_chunk_ids\x18\x02 \x03(\x0b\x32-.search.QueryResponse.FileNameToChunkIdsEntry\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x1aM\n\x17\x46ileNameToChunkIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.search.StringList:\x02\x38\x01\"9\n\x0cStoreRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x18\n\x10source_file_name\x18\x02 \x01(\t\"B\n\rStoreResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.search.StatusCode\x12\r\n\x05\x65rror\x18\x02 \x01(\t*G\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x14\n\x10INVALID_ARGUMENT\x10\x02\x12\x0c\n\x08INTERNAL\x10\x03\x32{\n\rSearchService\x12\x34\n\x05Query\x12\x14.search.QueryRequest\x1a\x15.search.QueryResponse\x12\x34\n\x05Store\x12\x14.search.StoreRequest\x1a\x15.search.StoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_QUERYRESPONSE_FILENAMETOCHUNKIDSENTRY']._loaded_options = None
  _globals['_QUERYRESPONSE_FILENAMETOCHUNKIDSENTRY']._serialized_options = b'8\001'
  _globals['_STATUSCODE']._serialized_start=704
  _globals['_STATUSCODE']._serialized_end=775
  _globals['_DOCUMENT']._serialized_start=25
  _globals['_DOCUMENT']._serialized_end=169
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=122
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=169
  _globals['_QUERYREQUEST']._serialized_start=172
  _globals['_QUERYREQUEST']._serialized_end=318
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_start=272
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_end=318
  _globals['_STRINGLIST']._serialized_start=320
  _globals['_STRINGLIST']._serialized_end=348
  _globals['_QUERYRESPONSE']._serialized_start=351
  _globals['_QUERYRESPONSE']._serialized_end=575
  _globals['_QUERYRESPONSE_FILENAMETOCHUNKIDSENTRY']._serialized_start=498
  _globals['_QUERYRESPONSE_FILENAMETOCHUNKIDSENTRY']._serialized_end=575
  _globals['_STOREREQUEST']._serialized_start=577
  _globals['_STOREREQUEST']._serialized_end=634
  _globals['_STORERESPONSE']._serialized_start=636
  _globals['_STORERESPONSE']._serialized_end=702
  _globals['_SEARCHSERVICE']._serialized_start=777
  _globals['_SEARCHSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
