# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"\x83\x01\n\x08\x44ocument\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x30\n\x08metadata\x18\x02 \x03(\x0b\x32\x1e.search.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x92\x01\n\x0cQueryRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x32\n\x07\x66ilters\x18\x03 \x03(\x0b\x32!.search.QueryRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"g\n\rQueryResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.search.StatusCode\x12#\n\tdocuments\x18\x02 \x03(\x0b\x32\x10.search.Document\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"<\n\x0cStoreRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x1b\n\x13metadata_file_names\x18\x02 \x03(\t\"B\n\rStoreResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.search.StatusCode\x12\r\n\x05\x65rror\x18\x02 \x01(\t*G\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x14\n\x10INVALID_ARGUMENT\x10\x02\x12\x0c\n\x08INTERNAL\x10\x03\x32{\n\rSearchService\x12\x34\n\x05Query\x12\x14.search.QueryRequest\x1a\x15.search.QueryResponse\x12\x34\n\x05Store\x12\x14.search.StoreRequest\x1a\x15.search.StoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_STATUSCODE']._serialized_start=542
  _globals['_STATUSCODE']._serialized_end=613
  _globals['_DOCUMENT']._serialized_start=25
  _globals['_DOCUMENT']._serialized_end=156
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=109
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=156
  _globals['_QUERYREQUEST']._serialized_start=159
  _globals['_QUERYREQUEST']._serialized_end=305
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_start=259
  _globals['_QUERYREQUEST_FILTERSENTRY']._serialized_end=305
  _globals['_QUERYRESPONSE']._serialized_start=307
  _globals['_QUERYRESPONSE']._serialized_end=410
  _globals['_STOREREQUEST']._serialized_start=412
  _globals['_STOREREQUEST']._serialized_end=472
  _globals['_STORERESPONSE']._serialized_start=474
  _globals['_STORERESPONSE']._serialized_end=540
  _globals['_SEARCHSERVICE']._serialized_start=615
  _globals['_SEARCHSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
